### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by roastedcheese**
honestly quite incredible

### CODE REVIEW

**Review by NotAShelf — COMMENTED** [review]
pretty shrimple

**Comment by NotAShelf** [comment]
follow commit format pls

**Comment by roastedcheese** [comment]
would that be like "README: fix typos"?

**Comment by NotAShelf** [comment]
I generally use docs: for readme, you can see commit history of the readme

**Comment by roastedcheese** [comment]
better?

**Comment by NotAShelf** [comment]
looks good, thanks

**Review by NotAShelf — APPROVED** [review]

**Pull request merged**
